// create an empty modbus client
var ModbusRTU = require("modbus-serial");
var client = new ModbusRTU();

// open connection to a serial port
var serialPort = process.env.SERIAL || "/dev/ttyUSB0";
client.connectRTU(serialPort, { baudRate: 115200 });

function getValue(name, callback) {
  return new Promise((resolve, reject) => {
    var register = registers[name];
    // console.log(register);
    client
      .readInputRegisters(register.address, register.size)
      .then((result) => {
        if (register.size == 1) value = result.data[0] / register.times;
        else if (register.size == 2)
          value = (result.data[0] | (result.data[1] << 16)) / register.times;

        resolve({
          variableName: register.variableName,
          description: register.description,
          unit: register.unit,
          value: value,
        });
      });
  });
}

var registers = {
  CHARGING_EQUIPMENT_RATED_INPUT_VOLTAGE: {
    variableName: "Charging equipment rated input voltage",
    address: 0x3000,
    description: "PV array rated voltage",
    unit: "V",
    times: 100,
    size: 1,
  },
  CHARGING_EQUIPMENT_RATED_INPUT_CURRENT: {
    variableName: "Charging equipment rated input current",
    address: 0x3001,
    description: "PV array rated current",
    unit: "A",
    times: 100,
    size: 1,
  },
  CHARGING_EQUIPMENT_RATED_INPUT_POWER: {
    variableName: "Charging equipment rated input power",
    address: 0x3002,
    description: "PV array rated power",
    unit: "W",
    times: 100,
    size: 2,
  },
  CHARGING_EQUIPMENT_RATED_INPUT_POWER_L: {
    variableName: "Charging equipment rated input power L",
    address: 0x3002,
    description: "PV array rated power (low 16 bits)",
    unit: "W",
    times: 100,
    size: 1,
  },
  CHARGING_EQUIPMENT_RATED_INPUT_POWER_H: {
    variableName: "Charging equipment rated input power H",
    address: 0x3003,
    description: "PV array rated power (high 16 bits)",
    unit: "W",
    times: 100,
    size: 1,
  },
  CHARGING_EQUIPMENT_RATED_OUTPUT_VOLTAGE: {
    variableName: "Charging equipment rated output voltage",
    address: 0x3004,
    description: "Battery's voltage",
    unit: "V",
    times: 100,
    size: 1,
  },
  CHARGING_EQUIPMENT_RATED_OUTPUT_CURRENT: {
    variableName: "Charging equipment rated output current",
    address: 0x3005,
    description: "Rated charging current to battery",
    unit: "A",
    times: 100,
    size: 1,
  },
  CHARGING_EQUIPMENT_RATED_OUTPUT_POWER: {
    variableName: "Charging equipment rated output power",
    address: 0x3006,
    description: "Rated charging power to battery",
    unit: "W",
    times: 100,
    size: 2,
  },
  CHARGING_EQUIPMENT_RATED_OUTPUT_POWER_L: {
    variableName: "Charging equipment rated output power L",
    address: 0x3006,
    description: "Rated charging power to battery H",
    unit: "W",
    times: 100,
    size: 1,
  },
  CHARGING_EQUIPMENT_RATED_OUTPUT_POWER_H: {
    variableName: "Charging equipment rated output power H",
    address: 0x3007,
    description: "Charging equipment rated output power H",
    unit: "W",
    times: 100,
    size: 1,
  },
  CHARGING_MODE: {
    variableName: "Charging mode",
    address: 0x3008,
    description: "0001H-PWM",
    unit: "I",
    times: 1,
    size: 1,
  },
  RATED_OUTPUT_CURRENT_OF_LOAD: {
    variableName: "Rated output current of load",
    address: 0x300e,
    description: "Rated output current of load",
    unit: "A",
    times: 100,
    size: 1,
  },
  CHARGING_EQUIPMENT_INPUT_VOLTAGE: {
    variableName: "Charging equipment input voltage",
    address: 0x3100,
    description: "Solar charge controller--PV array voltage",
    unit: "V",
    times: 100,
    size: 1,
  },
  CHARGING_EQUIPMENT_INPUT_CURRENT: {
    variableName: "Charging equipment input current",
    address: 0x3101,
    description: "Solar charge controller--PV array current",
    unit: "A",
    times: 100,
    size: 1,
  },
  CHARGING_EQUIPMENT_INPUT_POWER: {
    variableName: "Charging equipment input power",
    address: 0x3102,
    description: "Solar charge controller--PV array power",
    unit: "W",
    times: 100,
    size: 2,
  },
  CHARGING_EQUIPMENT_INPUT_POWER_L: {
    variableName: "Charging equipment input power L",
    address: 0x3102,
    description: "Solar charge controller--PV array power",
    unit: "W",
    times: 100,
    size: 1,
  },
  CHARGING_EQUIPMENT_INPUT_POWER_H: {
    variableName: "Charging equipment input power H",
    address: 0x3103,
    description: "Charging equipment input power H",
    unit: "W",
    times: 100,
    size: 1,
  },
  CHARGING_EQUIPMENT_OUTPUT_VOLTAGE: {
    variableName: "Charging equipment output voltage",
    address: 0x3104,
    description: "Battery voltage",
    unit: "V",
    times: 100,
    size: 1,
  },
  CHARGING_EQUIPMENT_OUTPUT_CURRENT: {
    variableName: "Charging equipment output current",
    address: 0x3105,
    description: "Battery charging current",
    unit: "A",
    times: 100,
    size: 1,
  },
  CHARGING_EQUIPMENT_OUTPUT_POWER: {
    variableName: "Charging equipment output power",
    address: 0x3106,
    description: "Battery charging power",
    unit: "W",
    times: 100,
    size: 2,
  },
  CHARGING_EQUIPMENT_OUTPUT_POWER_L: {
    variableName: "Charging equipment output power L",
    address: 0x3106,
    description: "Battery charging power",
    unit: "W",
    times: 100,
    size: 1,
  },
  CHARGING_EQUIPMENT_OUTPUT_POWER_H: {
    variableName: "Charging equipment output power H",
    address: 0x3107,
    description: "Charging equipment output power H",
    unit: "W",
    times: 100,
    size: 1,
  },
  DISCHARGING_EQUIPMENT_OUTPUT_VOLTAGE: {
    variableName: "Discharging equipment output voltage",
    address: 0x310c,
    description: "Load voltage",
    unit: "V",
    times: 100,
    size: 1,
  },
  DISCHARGING_EQUIPMENT_OUTPUT_CURRENT: {
    variableName: "Discharging equipment output current",
    address: 0x310d,
    description: "Load current",
    unit: "A",
    times: 100,
    size: 1,
  },
  DISCHARGING_EQUIPMENT_OUTPUT_POWER: {
    variableName: "Discharging equipment output power",
    address: 0x310e,
    description: "Load power",
    unit: "W",
    times: 100,
    size: 2,
  },
  DISCHARGING_EQUIPMENT_OUTPUT_POWER_L: {
    variableName: "Discharging equipment output power L",
    address: 0x310e,
    description: "Load power L",
    unit: "W",
    times: 100,
    size: 1,
  },
  DISCHARGING_EQUIPMENT_OUTPUT_POWER_H: {
    variableName: "Discharging equipment output power H",
    address: 0x310f,
    description: "Discharging equipment output power H",
    unit: "W",
    times: 100,
    size: 1,
  },
  BATTERY_TEMPERATURE: {
    variableName: "Battery Temperature",
    address: 0x3110,
    description: "Battery Temperature",
    unit: "C",
    times: 100,
    size: 1,
  },
  TEMPERATURE_INSIDE_EQUIPMENT: {
    variableName: "Temperature inside equipment",
    address: 0x3111,
    description: "Temperature inside case",
    unit: "C",
    times: 100,
    size: 1,
  },
  POWER_COMPONENTS_TEMPERATURE: {
    variableName: "Power components temperature",
    address: 0x3112,
    description:
      "Heat sink surface temperature of equipments' power components",
    unit: "C",
    times: 100,
    size: 1,
  },
  BATTERY_SOC: {
    variableName: "Battery SOC",
    address: 0x311a,
    description: "The percentage of battery's remaining capacity",
    unit: "PC",
    times: 1,
    size: 1,
  },
  REMOTE_BATTERY_TEMPERATURE: {
    variableName: "Remote battery temperature",
    address: 0x311b,
    description: "The battery tempeture measured by remote temperature sensor",
    unit: "C",
    times: 100,
    size: 1,
  },
  BATTERYS_REAL_RATED_POWER: {
    variableName: "Battery's real rated power",
    address: 0x311d,
    description: "Current system rated votlage. 1200, 2400 represent 12V, 24V",
    unit: "V",
    times: 100,
    size: 1,
  },
  BATTERY_STATUS: {
    variableName: "Battery status",
    address: 0x3200,
    description:
      "D3-D0: 01H Overvolt , 00H Normal , 02H Under Volt, 03H Low Volt Disconnect, 04H Fault D7-D4: 00H Normal, 01H;Over Temp.(Higher than the warning settings), 02H Low Temp.( Lower than the warning settings), D8: Battery inerternal resistance abnormal 1, normal 0 D15: 1-Wrong identification for rated voltage",
    unit: "I",
    times: 1,
    size: 1,
  },
  CHARGING_EQUIPMENT_STATUS: {
    variableName: "Charging equipment status",
    address: 0x3201,
    description:
      "D15-D14: Input volt status. 00 normal, 01 no power connected, 02H Higher volt input,;03H Input volt error. D13: Charging MOSFET is short. D12: Charging or Anti-reverse MOSFET is short. D11: Anti-reverse MOSFET is short. D10: Input is over current. D9: The load is Over current. D8: The load is short. D7: Load MOSFET is short. D4: PV Input is short. D3-2: Charging status. 00 No charging,01 Float,02 Boost,03 Equlization. D1: 0 Normal, 1 Fault. D0: 1 Running, 0 Standby.",
    unit: "I",
    times: 1,
    size: 1,
  },
  MAXIMUM_INPUT_VOLT_PV_TODAY: {
    variableName: "Maximum input volt (PV) today",
    address: 0x3300,
    description: "00: 00 Refresh every day",
    unit: "V",
    times: 100,
    size: 1,
  },
  MINIMUM_INPUT_VOLT_PV_TODAY: {
    variableName: "Minimum input volt (PV) today",
    address: 0x3301,
    description: "00: 00 Refresh every day",
    unit: "V",
    times: 100,
    size: 1,
  },
  MAXIMUM_BATTERY_VOLT_TODAY: {
    variableName: "Maximum battery volt today",
    address: 0x3302,
    description: "00: 00 Refresh every day",
    unit: "V",
    times: 100,
    size: 1,
  },
  MINIMUM_BATTERY_VOLT_TODAY: {
    variableName: "Minimum battery volt today",
    address: 0x3303,
    description: "00: 00 Refresh every day",
    unit: "V",
    times: 100,
    size: 1,
  },
  CONSUMED_ENERGY_TODAY: {
    variableName: "Consumed energy today",
    address: 0x3304,
    description: "00: 00 Clear every day",
    unit: "KWH",
    times: 100,
    size: 2,
  },
  CONSUMED_ENERGY_TODAY_L: {
    variableName: "Consumed energy today L",
    address: 0x3304,
    description: "00: 00 Clear every day",
    unit: "KWH",
    times: 100,
    size: 1,
  },
  CONSUMED_ENERGY_TODAY_H: {
    variableName: "Consumed energy today H",
    address: 0x3305,
    description: "Consumed energy today H",
    unit: "KWH",
    times: 100,
    size: 1,
  },
  CONSUMED_ENERGY_THIS_MONTH: {
    variableName: "Consumed energy this month",
    address: 0x3306,
    description: "00: 00 Clear on the first day of month",
    unit: "KWH",
    times: 100,
    size: 2,
  },
  CONSUMED_ENERGY_THIS_MONTH_L: {
    variableName: "Consumed energy this month L",
    address: 0x3306,
    description: "00: 00 Clear on the first day of month",
    unit: "KWH",
    times: 100,
    size: 1,
  },
  CONSUMED_ENERGY_THIS_MONTH_H: {
    variableName: "Consumed energy this month H",
    address: 0x3307,
    description: "Consumed energy this month H",
    unit: "KWH",
    times: 100,
    size: 1,
  },
  CONSUMED_ENERGY_THIS_YEAR: {
    variableName: "Consumed energy this year",
    address: 0x3308,
    description: "00: 00 Clear on 1, Jan.",
    unit: "KWH",
    times: 100,
    size: 2,
  },
  CONSUMED_ENERGY_THIS_YEAR_L: {
    variableName: "Consumed energy this year L",
    address: 0x3308,
    description: "00: 00 Clear on 1, Jan.",
    unit: "KWH",
    times: 100,
    size: 1,
  },
  CONSUMED_ENERGY_THIS_YEAR_H: {
    variableName: "Consumed energy this year H",
    address: 0x3309,
    description: "Consumed energy this year H",
    unit: "KWH",
    times: 100,
    size: 1,
  },
  TOTAL_CONSUMED_ENERGY: {
    variableName: "Total consumed energy",
    address: 0x330a,
    description: "Total consumed energy",
    unit: "KWH",
    times: 100,
    size: 2,
  },
  TOTAL_CONSUMED_ENERGY_L: {
    variableName: "Total consumed energy L",
    address: 0x330a,
    description: "Total consumed energy L",
    unit: "KWH",
    times: 100,
    size: 1,
  },
  TOTAL_CONSUMED_ENERGY_H: {
    variableName: "Total consumed energy H",
    address: 0x330b,
    description: "Total consumed energy H",
    unit: "KWH",
    times: 100,
    size: 1,
  },
  GENERATED_ENERGY_TODAY: {
    variableName: "Generated energy today",
    address: 0x330c,
    description: "00: 00 Clear every day.",
    unit: "KWH",
    times: 100,
    size: 2,
  },
  GENERATED_ENERGY_TODAY_L: {
    variableName: "Generated energy today L",
    address: 0x330c,
    description: "00: 00 Clear every day.",
    unit: "KWH",
    times: 100,
    size: 1,
  },
  GENERATED_ENERGY_TODAY_H: {
    variableName: "Generated energy today H",
    address: 0x330d,
    description: "Generated energy today H",
    unit: "KWH",
    times: 100,
    size: 1,
  },
  GENERATED_ENERGY_THIS_MONTH: {
    variableName: "Generated energy this month",
    address: 0x330e,
    description: "00: 00 Clear on the first day of month.",
    unit: "KWH",
    times: 100,
    size: 2,
  },
  GENERATED_ENERGY_THIS_MONTH_L: {
    variableName: "Generated energy this month L",
    address: 0x330e,
    description: "00: 00 Clear on the first day of month.",
    unit: "KWH",
    times: 100,
    size: 1,
  },
  GENERATED_ENERGY_THIS_MONTH_H: {
    variableName: "Generated energy this month H",
    address: 0x330f,
    description: "Generated energy this month H",
    unit: "KWH",
    times: 100,
    size: 1,
  },
  GENERATED_ENERGY_THIS_YEAR: {
    variableName: "Generated energy this year",
    address: 0x3310,
    description: "00: 00 Clear on 1, Jan.",
    unit: "KWH",
    times: 100,
    size: 2,
  },
  GENERATED_ENERGY_THIS_YEAR_L: {
    variableName: "Generated energy this year L",
    address: 0x3310,
    description: "00: 00 Clear on 1, Jan.",
    unit: "KWH",
    times: 100,
    size: 1,
  },
  GENERATED_ENERGY_THIS_YEAR_H: {
    variableName: "Generated energy this year H",
    address: 0x3311,
    description: "Generated energy this year H",
    unit: "KWH",
    times: 100,
    size: 1,
  },
  TOTAL_GENERATED_ENERGY: {
    variableName: "Total generated energy",
    address: 0x3312,
    description: "Total generated energy",
    unit: "KWH",
    times: 100,
    size: 2,
  },
  TOTAL_GENERATED_ENERGY_L: {
    variableName: "Total generated energy L",
    address: 0x3312,
    description: "Total generated energy L",
    unit: "KWH",
    times: 100,
    size: 1,
  },
  TOTAL_GENERATED_ENERGY_H: {
    variableName: "Total Generated energy H",
    address: 0x3313,
    description: "Total Generated energy H",
    unit: "KWH",
    times: 100,
    size: 1,
  },
  CARBON_DIOXIDE_REDUCTION: {
    variableName: "Carbon dioxide reduction",
    address: 0x3314,
    description:
      "Saving 1 Kilowatt=Reduction 0.997KG''Carbon dioxide ''=Reduction 0.272KG''Carton''",
    unit: "Ton",
    times: 100,
    size: 2,
  },
  CARBON_DIOXIDE_REDUCTION_L: {
    variableName: "Carbon dioxide reduction L",
    address: 0x3314,
    description:
      "Saving 1 Kilowatt=Reduction 0.997KG''Carbon dioxide ''=Reduction 0.272KG''Carton''",
    unit: "Ton",
    times: 100,
    size: 1,
  },
  CARBON_DIOXIDE_REDUCTION_H: {
    variableName: "Carbon dioxide reduction H",
    address: 0x3315,
    description: "Carbon dioxide reduction H",
    unit: "Ton",
    times: 100,
    size: 1,
  },
  BATTERY_CURRENT: {
    variableName: "Battery Current",
    address: 0x331b,
    description:
      "The net battery current,charging current minus the discharging one. The positive value represents charging;and negative, discharging.",
    unit: "A",
    times: 100,
    size: 2,
  },
  BATTERY_CURRENT_L: {
    variableName: "Battery Current L",
    address: 0x331b,
    description:
      "The net battery current,charging current minus the discharging one. The positive value represents;charging and negative, discharging.",
    unit: "A",
    times: 100,
    size: 1,
  },
  BATTERY_CURRENT_H: {
    variableName: "Battery Current H",
    address: 0x331c,
    description: "Battery Current H",
    unit: "A",
    times: 100,
    size: 1,
  },
  BATTERY_TEMP: {
    variableName: "Battery Temp.",
    address: 0x331d,
    description: "Battery Temp.",
    unit: "C",
    times: 100,
    size: 1,
  },
  AMBIENT_TEMP: {
    variableName: "Ambient Temp.",
    address: 0x331e,
    description: "Ambient Temp.",
    unit: "C",
    times: 100,
    size: 1,
  },
  BATTERY_TYPE: {
    variableName: "Battery Type",
    address: 0x9000,
    description:
      "0001H- Sealed , 0002H- GEL, 0003H- Flooded, 0000H- User defined",
    unit: "I",
    times: 1,
    size: 1,
  },
  BATTERY_CAPACITY: {
    variableName: "Battery Capacity",
    address: 0x9001,
    description: "Rated capacity of the battery",
    unit: "AH",
    times: 1,
    size: 1,
  },
  TEMPERATURE_COMPENSATION_COEFFICIENT: {
    variableName: "Temperature compensation coefficient",
    address: 0x9002,
    description: "Range 0-9 mV/�C/2V",
    unit: "I",
    times: 100,
    size: 1,
  },
  HIGH_VOLT_DISCONNECT: {
    variableName: "High Volt.disconnect",
    address: 0x9003,
    description: "High Volt.disconnect",
    unit: "V",
    times: 100,
    size: 1,
  },
  CHARGING_LIMIT_VOLTAGE: {
    variableName: "Charging limit voltage",
    address: 0x9004,
    description: "Charging limit voltage",
    unit: "V",
    times: 100,
    size: 1,
  },
  OVER_VOLTAGE_RECONNECT: {
    variableName: "Over voltage reconnect",
    address: 0x9005,
    description: "Over voltage reconnect",
    unit: "V",
    times: 100,
    size: 1,
  },
  EQUALIZATION_VOLTAGE: {
    variableName: "Equalization voltage",
    address: 0x9006,
    description: "Equalization voltage",
    unit: "V",
    times: 100,
    size: 1,
  },
  BOOST_VOLTAGE: {
    variableName: "Boost voltage",
    address: 0x9007,
    description: "Boost voltage",
    unit: "V",
    times: 100,
    size: 1,
  },
  FLOAT_VOLTAGE: {
    variableName: "Float voltage",
    address: 0x9008,
    description: "Float voltage",
    unit: "V",
    times: 100,
    size: 1,
  },
  BOOST_RECONNECT_VOLTAGE: {
    variableName: "Boost reconnect voltage",
    address: 0x9009,
    description: "Boost reconnect voltage",
    unit: "V",
    times: 100,
    size: 1,
  },
  LOW_VOLTAGE_RECONNECT: {
    variableName: "Low voltage reconnect",
    address: 0x900a,
    description: "Low voltage reconnect",
    unit: "V",
    times: 100,
    size: 1,
  },
  UNDER_VOLTAGE_RECOVER: {
    variableName: "Under voltage recover",
    address: 0x900b,
    description: "Under voltage recover",
    unit: "V",
    times: 100,
    size: 1,
  },
  UNDER_VOLTAGE_WARNING: {
    variableName: "Under voltage warning",
    address: 0x900c,
    description: "Under voltage warning",
    unit: "V",
    times: 100,
    size: 1,
  },
  LOW_VOLTAGE_DISCONNECT: {
    variableName: "Low voltage disconnect",
    address: 0x900d,
    description: "Low voltage disconnect",
    unit: "V",
    times: 100,
    size: 1,
  },
  DISCHARGING_LIMIT_VOLTAGE: {
    variableName: "Discharging limit voltage",
    address: 0x900e,
    description: "Discharging limit voltage",
    unit: "V",
    times: 100,
    size: 1,
  },
  REAL_TIME_CLOCK_1: {
    variableName: "Real time clock 1",
    address: 0x9013,
    description:
      "D7-0 Sec, D15-8 Min.(Year,Month,Day,Min,Sec.should be writed simultaneously)",
    unit: "I",
    times: 1,
    size: 1,
  },
  REAL_TIME_CLOCK_2: {
    variableName: "Real time clock 2",
    address: 0x9014,
    description: "D7-0 Hour, D15-8 Day",
    unit: "I",
    times: 1,
    size: 1,
  },
  REAL_TIME_CLOCK_3: {
    variableName: "Real time clock 3",
    address: 0x9015,
    description: "D7-0 Month, D15-8 Year",
    unit: "I",
    times: 1,
    size: 1,
  },
  EQUALIZATION_CHARGING_CYCLE: {
    variableName: "Equalization charging cycle",
    address: 0x9016,
    description: "Interval days of auto equalization charging in cycle Day",
    unit: "I",
    times: 1,
    size: 1,
  },
  BATTERY_TEMPERATURE_WARNING_UPPER_LIMIT: {
    variableName: "Battery temperature warning upper limit",
    address: 0x9017,
    description: "Battery temperature warning upper limit",
    unit: "C",
    times: 100,
    size: 1,
  },
  BATTERY_TEMPERATURE_WARNING_LOWER_LIMIT: {
    variableName: "Battery temperature warning lower limit",
    address: 0x9018,
    description: "Battery temperature warning lower limit",
    unit: "C",
    times: 100,
    size: 1,
  },
  CONTROLLER_INNER_TEMPERATURE_UPPER_LIMIT: {
    variableName: "Controller inner temperature upper limit",
    address: 0x9019,
    description: "Controller inner temperature upper limit",
    unit: "C",
    times: 100,
    size: 1,
  },
  CONTROLLER_INNER_TEMPERATURE_UPPER_LIMIT_RECOVER: {
    variableName: "Controller inner temperature upper limit recover",
    address: 0x901a,
    description:
      "After Over Temperature, system recover;once it drop to lower than this value",
    unit: "C",
    times: 100,
    size: 1,
  },
  POWER_COMPONENT_TEMPERATURE_UPPER_LIMIT: {
    variableName: "Power component temperature upper limit",
    address: 0x901b,
    description:
      "Warning when surface temperature of power components;higher than this value, and charging and discharging stop",
    unit: "C",
    times: 100,
    size: 1,
  },
  POWER_COMPONENT_TEMPERATURE_UPPER_LIMIT_RECOVER: {
    variableName: "Power component temperature upper limit recover",
    address: 0x901c,
    description:
      "Recover once power components temperature;lower than this value",
    unit: "C",
    times: 100,
    size: 1,
  },
  LINE_IMPEDANCE: {
    variableName: "Line Impedance",
    address: 0x901d,
    description: "The resistance of the connectted wires.",
    unit: "MO",
    times: 100,
    size: 1,
  },
  NIGHT_TIMETHRESHOLD_VOLT_NTTV: {
    variableName: "Night TimeThreshold Volt.(NTTV)",
    address: 0x901e,
    description:
      " PV lower lower than this value, controller would detect it as sundown",
    unit: "V",
    times: 100,
    size: 1,
  },
  LIGHT_SIGNAL_STARTUP_NIGHT_DELAY_TIME: {
    variableName: "Light signal startup (night) delay time",
    address: 0x901f,
    description:
      "PV voltage lower than NTTV, and duration exceeds the Light;signal startup (night) delay time, controller would detect it as night time.",
    unit: "MIN",
    times: 1,
    size: 1,
  },
  DAY_TIME_THRESHOLD_VOLT_DTTV: {
    variableName: "Day Time Threshold Volt.(DTTV)",
    address: 0x9020,
    description:
      "PV voltage higher than this value, controller would detect it as sunrise",
    unit: "V",
    times: 100,
    size: 1,
  },
  LIGHT_SIGNAL_TURN_OFF_DAY_DELAY_TIME: {
    variableName: "Light signal turn off(day) delay time",
    address: 0x9021,
    description:
      "PV voltage higher than DTTV, and duration exceeds Light signal;turn off(day) delay time delay time, controller would detect it as daytime.",
    unit: "MIN",
    times: 1,
    size: 1,
  },
  LOAD_CONTROLING_MODES: {
    variableName: "Load controling modes",
    address: 0x903d,
    description:
      "0000H Manual Control, 0001H Light ON/OFF, 0002H Light ON+ Timer/, 0003H Time Control",
    unit: "I",
    times: 1,
    size: 1,
  },
  WORKING_TIME_LENGTH_1: {
    variableName: "Working time length 1",
    address: 0x903e,
    description: "The length of load output timer1, D15-D8,hour, D7-D0, minute",
    unit: "I",
    times: 1,
    size: 1,
  },
  WORKING_TIME_LENGTH_2: {
    variableName: "Working time length 2",
    address: 0x903f,
    description:
      "The length of load output timer2, D15-D8, hour, D7-D0, minute",
    unit: "I",
    times: 1,
    size: 1,
  },
  TURN_ON_TIMING_1_SEC: {
    variableName: "Turn on timing 1 sec",
    address: 0x9042,
    description: "Turn on timing 1 sec",
    unit: "SEC",
    times: 1,
    size: 1,
  },
  TURN_ON_TIMING_1_MIN: {
    variableName: "Turn on timing 1 min",
    address: 0x9043,
    description: "Turn on timing 1 min",
    unit: "MIN",
    times: 1,
    size: 1,
  },
  TURN_ON_TIMING_1_HOUR: {
    variableName: "Turn on timing 1 hour",
    address: 0x9044,
    description: "Turn on timing 1 hour",
    unit: "HOUR",
    times: 1,
    size: 1,
  },
  TURN_OFF_TIMING_1_SEC: {
    variableName: "Turn off timing 1 sec",
    address: 0x9045,
    description: "Turn off timing 1 sec",
    unit: "SEC",
    times: 1,
    size: 1,
  },
  TURN_OFF_TIMING_1_MIN: {
    variableName: "Turn off timing 1 min",
    address: 0x9046,
    description: "Turn off timing 1 min",
    unit: "MIN",
    times: 1,
    size: 1,
  },
  TURN_OFF_TIMING_1_HOUR: {
    variableName: "Turn off timing 1 hour",
    address: 0x9047,
    description: "Turn off timing 1 hour",
    unit: "HOUR",
    times: 1,
    size: 1,
  },
  TURN_ON_TIMING_2_SEC: {
    variableName: "Turn on timing 2 sec",
    address: 0x9048,
    description: "Turn on timing 2 sec",
    unit: "SEC",
    times: 1,
    size: 1,
  },
  TURN_ON_TIMING_2_MIN: {
    variableName: "Turn on timing 2 min",
    address: 0x9049,
    description: "Turn on timing 2 min",
    unit: "MIN",
    times: 1,
    size: 1,
  },
  TURN_ON_TIMING_2_HOUR: {
    variableName: "Turn on timing 2 hour",
    address: 0x904a,
    description: "Turn on timing 2 hour",
    unit: "HOUR",
    times: 1,
    size: 1,
  },
  TURN_OFF_TIMING_2_SEC: {
    variableName: "Turn off timing 2 sec",
    address: 0x904b,
    description: "Turn off timing 2 sec",
    unit: "SEC",
    times: 1,
    size: 1,
  },
  TURN_OFF_TIMING_2_MIN: {
    variableName: "Turn off timing 2 min",
    address: 0x904c,
    description: "Turn off timing 2 min",
    unit: "MIN",
    times: 1,
    size: 1,
  },
  TURN_OFF_TIMING_2_HOUR: {
    variableName: "Turn off timing 2 hour",
    address: 0x904d,
    description: "Turn off timing 2 hour",
    unit: "HOUR",
    times: 1,
    size: 1,
  },
  LENGTH_OF_NIGHT: {
    variableName: "Length of night",
    address: 0x9065,
    description:
      "Set default values of the whole night length of time. D15-D8,hour, D7-D0, minute",
    unit: "I",
    times: 1,
    size: 1,
  },
  BATTERY_RATED_VOLTAGE_CODE: {
    variableName: "Battery rated voltage code",
    address: 0x9067,
    description: "0, auto recognize. 1-12V, 2-24V",
    unit: "I",
    times: 1,
    size: 1,
  },
  LOAD_TIMING_CONTROL_SELECTION: {
    variableName: "Load timing control selection",
    address: 0x9069,
    description:
      "Selected timeing period of the load.0, using one timer, 1-using two timer,;likewise.",
    unit: "I",
    times: 1,
    size: 1,
  },
  DEFAULT_LOAD_ON_OFF_IN_MANUAL_MODE: {
    variableName: "Default Load On/Off in manual mode",
    address: 0x906a,
    description: "0-off, 1-on",
    unit: "I",
    times: 1,
    size: 1,
  },
  EQUALIZE_DURATION: {
    variableName: "Equalize duration",
    address: 0x906b,
    description: "Usually 60-120 minutes.",
    unit: "MIN",
    times: 1,
    size: 1,
  },
  BOOST_DURATION: {
    variableName: "Boost duration",
    address: 0x906c,
    description: "Usually 60-120 minutes.",
    unit: "MIN",
    times: 1,
    size: 1,
  },
  DISCHARGING_PERCENTAGE: {
    variableName: "Discharging percentage",
    address: 0x906d,
    description:
      "Usually 20%-80%. The percentage of battery's remaining capacity when stop charging",
    unit: "PC",
    times: 1,
    size: 1,
  },
  CHARGING_PERCENTAGE: {
    variableName: "Charging percentage",
    address: 0x906e,
    description: "Depth of charge, 20%-100%.",
    unit: "PC",
    times: 1,
    size: 1,
  },
  MANAGEMENT_MODES_OF_BATTERY_CHARGING_AND_DISCHARGING: {
    variableName: "Management modes of battery charging and discharging",
    address: 0x9070,
    description:
      "Management modes of battery;charge and discharge, voltage compensation : 0 and SOC : 1.",
    unit: "I",
    times: 1,
    size: 1,
  },
};

module.exports = { client: client, getValue: getValue };
